Add tests

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -48,6 +48,37 @@ workflows:
         - content: |
             #!/bin/bash
             gmsaas auth whoami
+  test-api-token:
+    before_run:
+      - audit-this-step
+    steps:
+    - change-workdir:
+        title: Switch working dir to test / _tmp dir
+        description: |-
+          To prevent step testing issues, like referencing relative
+          files with just './some-file' in the step's code, which would
+          work for testing the step from this directory directly
+          but would break if the step is included in another `bitrise.yml`.
+        run_if: true
+        inputs:
+        - path: ./_tmp
+        - is_create_path: true
+    - path::./:
+        title: Genymotion SaaS - Install gmsaas
+        run_if: "true"
+        inputs:
+        - gmsaas_version: "1.11.0"
+        - api_token: $GMCLOUD_SAAS_API_TOKEN
+    - script:
+        inputs:
+        - content: |
+            #!/bin/bash
+            gmsaas doctor
+            retVal=$?
+            if [ $retVal -ne 0 ]; then
+              echo "Error"
+            fi
+            exit $retVal
 
 
 
